name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: ssh to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_SSH_HOST }}
          password: ${{ secrets.DEPLOY_SSH_PASSPHRASE }}
          username: ${{ secrets.DEPLOY_SSH_USER }}
          script: |
            cd tvendors
            git pull
            cd client
            npm run build
            pm2 restart all